### ISSUE TITLE
Which Arduino version this supports?

### ISSUE THREAD

**Issue by kittenarmy** [holgerlembke/st7567sfGK#3]
I'm trying to compile in 1.8.19 for Nano with ATmega 328P but get errors:

```
basic_st7567sfGK.ino: In function 'void setup()':

basic_st7567sfGK:32:36: error: no matching function for call to 'TwoWire::begin(const byte&, const byte&, long int)'

   Wire.begin(PinSDA, PinSCL, 400000);
```

**Comment by holgerlembke** [comment]
I use IDE 2.3.2. st7567sfGK  was developed with esp8266 as µC...

So this might be an oversight, that it does not work on all plattforms. Last parameter is bus frequency, I remember that it has been done with a separate function call in older versions. Remove it and bus frequency will fall back to standard 100 kHz.

You might use 

```
 Wire.begin();
```
and use the standard I2C ports for your plattform. Or

```
 Wire.begin(PinSDA,PinSCL);
```
to select SDA and SCL pin.
